name: Generate Snake

on:
  # හැම පැය 12කට වරක්ම ස්වයංක්‍රීයව ක්‍රියාත්මක වේ
  schedule:
    - cron: "0 */12 * * *" 
  
  # ඕනෑම වෙලාවක අතින් (Manually) Run කරගන්න පුළුවන්
  workflow_dispatch:
  
  # Main හෝ master branch එකට code push කළ විට ක්‍රියාත්මක වේ
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
